### ISSUE TITLE
Mica allows users to sign up and skip the approval process in Agate

### ISSUE THREAD

**Issue by gflcampos** [obiba/mica2#4139]
Note: I have disabled the "Sign-up with password" option.

When signing up, the user account is automatically created in Agate with status "Approved", skipping the approval by an Agate admin.

Is this a bug or the intended behaviour? It seems odd that users are able to skip account approval by simply registering in Mica instead of directly in Agate.

**Comment by ymarcon** [comment]
When the user joins through an application (Mica), the status of the new user is created with `ACTIVE` status if a password is provided, otherwise the `APPROVED` status is applied. The idea was that it is not a sign up out of the blue, there is a context which is the application (Mica).

Of course this behavior could be improved in the way that it could be an application's setting (`application` as defined by Agate).

**Comment by gflcampos** [comment]
Thanks!

I get that there is some context because Mica needs to know the app key in order to create the user. However, because the registration is open in Mica, I'm not sure that the context is sufficient to legitimize a new user.
Anyone is able to create as many users as they wish through Mica, which I would say is not desirable.

I think the improvement you propose sounds good! Is this something that would take much effort to implement? We are available to help, if necessary.

**Comment by ymarcon** [comment]
I think it is simple to implement: adding a new property to the application model, updating the application form UI accordingly and using this setting when a user signups in the context of the application.

**Comment by gflcampos** [comment]
So, I am now using the Agate version currently on the master branch and I can see the new "User Approved on Sign up" setting for applications.
When I try to sign up through Mica, I get an error message "error.unhandledException" and the Agate logs show:

```
2021-03-04 12:29:42.240  WARN 80 --- [ qtp89144445-22] o.glassfish.jersey.servlet.WebComponent  : A servlet request to the URI https://agate:8444/auth/ws/users/_join contains form parameters in the request body but the request body has been consumed by the servlet or a servlet filter accessing the request parameters. Only resource methods using @FormParam will work as expected. Resource methods consuming the request body by other means will not work as expected.
2021-03-04 12:29:43.018  WARN 80 --- [ qtp89144445-22] o.o.j.e.UnhandledExceptionMapper         : Exception catched by UnhandledExceptionMapper

java.lang.NullPointerException: null
   at org.obiba.agate.web.rest.user.UsersPublicResource.create(UsersPublicResource.java:227)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:498)
   at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
   at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
   at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
   at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
   at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
   at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
   at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
   at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
   at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
   at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
   at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
   at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
   at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
   at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
   at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
   at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
   at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
   at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
   at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
   at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
   at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
   at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
   at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
   at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:51)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
   at org.obiba.agate.web.filter.ClickjackingHttpHeadersFilter.doFilter(ClickjackingHttpHeadersFilter.java:41)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
   at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
   at org.obiba.agate.config.WebConfiguration$NoTraceFilter.doFilter(WebConfiguration.java:338)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
   at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:215)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
   at org.obiba.shiro.web.filter.AuthenticationFilter.doFilterInternal(AuthenticationFilter.java:158)
   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
   at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
   at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
   at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
   at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
   at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
   at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
   at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
   at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
   at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
   at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724)
   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
   at org.eclipse.jetty.server.Server.handle(Server.java:531)
   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
   at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
   at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
   at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:291)
   at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:151)
   at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
   at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
   at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
   at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
   at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
   at java.lang.Thread.run(Thread.java:748)
```

Howver, if I change the Mica application key to anything else other than what is was (which was the default `changeit`), everything works fine.
And afer this, if I change it back to `changeit`, I get the error again.

Note: when I say I changed the key, I only mean in Agate. So the fact that I changed the Mica key in Agate - but not in Mica itself - and everything (e.g. login, registration) works, does not make sense either.

**Comment by ymarcon** [comment]
@gflcampos please give it a try, should be fine now.

**Comment by ymarcon** [comment]
FYI there is a setting in Agate main config "Sign up page enabled" that you can disable, to be sure that user only sign up through the applications.

**Comment by gflcampos** [comment]
It works!
Thanks for the fix and for the tip about disabling the sign up in Agate, I think we will do that.
